package lk.gov.health.govcare.patient;

import lk.gov.health.govcare.common.*;import lk.gov.health.govcare.security.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.OffsetDateTime;import java.util.*;

@RestController @RequestMapping("/api/self-registration")
public class SelfRegistrationController {
 private final SqlSupport sql;private final CurrentUser current;private final SequenceService sequences;private final JsonSupport json;
 public SelfRegistrationController(SqlSupport sql,CurrentUser current,SequenceService sequences,JsonSupport json){this.sql=sql;this.current=current;this.sequences=sequences;this.json=json;}
 @GetMapping("/tokens") @PreAuthorize("hasAuthority('SELF_REGISTRATION_MANAGE')") public Map<String,Object> tokens(){GovCarePrincipal a=current.get();return Map.of("items",sql.list("select t.id::text,t.label,h.name hospital_name,h.city hospital_city,t.expires_at,t.uses_count,t.max_uses,t.status::text,t.created_at from patient_registration_tokens t join hospitals h on h.id=t.hospital_id where t.hospital_id=:hospital order by t.created_at desc limit 50",Map.of("hospital",a.hospitalId())));}
 @PostMapping("/tokens") @PreAuthorize("hasAuthority('SELF_REGISTRATION_MANAGE')") @Transactional public ResponseEntity<Map<String,Object>> createToken(@RequestBody Map<String,Object> in){GovCarePrincipal a=current.get();String token=UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-","").substring(0,16);String hash=hash(token);int max=Math.max(1,Math.min(Integer.parseInt(String.valueOf(in.getOrDefault("maxUses",100))),10000));int days=Math.max(1,Math.min(Integer.parseInt(String.valueOf(in.getOrDefault("validDays",14))),90));Map<String,Object>row=sql.required("insert into patient_registration_tokens(hospital_id,token_hash,label,expires_at,max_uses,status,created_by) values(:hospital,:hash,:label,now()+(:days||' days')::interval,:max,'active',:user) returning id::text,expires_at,uses_count,max_uses,status::text",map("hospital",a.hospitalId(),"hash",hash,"label",Objects.toString(in.getOrDefault("label","Patient self-registration QR")),"days",days,"max",max,"user",a.id()),"Unable to create registration token.");Map<String,Object>h=sql.required("select name,city from hospitals where id=:id",Map.of("id",a.hospitalId()),"Hospital not found.");Map<String,Object>out=new LinkedHashMap<>();out.put("token",token);out.put("id",row.get("id"));out.put("registrationUrl","/self-register/"+token);out.put("hospitalId",a.hospitalId().toString());out.put("hospitalName",h.get("name"));out.put("hospitalCity",h.get("city"));out.put("label",in.getOrDefault("label","Patient self-registration QR"));out.put("expiresAt",row.get("expires_at"));out.put("usesCount",row.get("uses_count"));out.put("maxUses",row.get("max_uses"));out.put("status",row.get("status"));return ResponseEntity.status(HttpStatus.CREATED).body(out);}
 @GetMapping("/tokens/{token}") public Map<String,Object> verify(@PathVariable String token){Map<String,Object>t=validToken(token,false);Map<String,Object>out=new LinkedHashMap<>();out.put("hospitalId",t.get("hospital_id"));out.put("hospitalName",t.get("hospital_name"));out.put("hospitalCity",t.get("hospital_city"));out.put("label",t.get("label"));out.put("expiresAt",t.get("expires_at"));out.put("usesCount",t.get("uses_count"));out.put("maxUses",t.get("max_uses"));out.put("status",t.get("status"));return out;}
 @PostMapping("/tokens/{token}/register") @Transactional public ResponseEntity<Map<String,Object>> register(@PathVariable String token,@RequestBody Map<String,Object> in){Map<String,Object>t=validToken(token,true);UUID hospital=UUID.fromString(String.valueOf(t.get("hospital_id")));String name=req(in,"fullName"),dob=req(in,"dateOfBirth"),gender=req(in,"gender"),phone=req(in,"phone"),address=req(in,"address");String nic=clean(in.get("nic")),passport=clean(in.get("passportNo"));Map<String,Object>dup=sql.one("select id::text,patient_no,full_name,status::text from patients where hospital_id=:hospital and status<>'deleted' and((:nic is not null and lower(nic)=lower(:nic)) or(:passport is not null and lower(passport_no)=lower(:passport)) or(phone=:phone and lower(full_name)=lower(:name))) limit 1",map("hospital",hospital,"nic",nic,"passport",passport,"phone",phone,"name",name)).orElse(null);if(dup!=null)return ResponseEntity.ok(Map.of("duplicate",true,"patient",dup));sequences.lock("govcare:"+hospital+":patients");String no=sequences.nextPatientNo(hospital);Map<String,Object>p=map("hospital",hospital,"no",no,"name",name,"nic",nic,"passport",passport,"dob",dob,"gender",gender,"phone",phone,"email",clean(in.get("email")),"address",address,"district",clean(in.get("district")),"province",clean(in.get("province")),"blood",clean(in.get("bloodGroup")),"language",Objects.toString(in.getOrDefault("languagePreference","en")),"emergency",json.write(Map.of("name",Objects.toString(in.getOrDefault("emergencyContactName","")),"phone",Objects.toString(in.getOrDefault("emergencyContactPhone","")))),"allergies",json.write(split(in.get("allergies"))),"chronic",json.write(split(in.get("chronicDiseases"))));Map<String,Object>row=sql.required("""
 insert into patients(hospital_id,patient_no,full_name,nic,passport_no,date_of_birth,gender,phone,email,address,district,province,blood_group,language_preference,emergency_contact,allergies,chronic_diseases,release_status,status)
 values(:hospital,:no,:name,:nic,:passport,cast(:dob as date),cast(:gender as gender_value),:phone,:email,:address,:district,:province,:blood,:language,cast(:emergency as jsonb),cast(:allergies as jsonb),cast(:chronic as jsonb),'internal','pending') returning id::text,patient_no,full_name,status::text,created_at
 """,p,"Unable to submit patient registration.");sql.update("update patient_registration_tokens set uses_count=uses_count+1,updated_at=now(),status=case when uses_count+1>=max_uses then 'completed'::record_status else status end where id=cast(:id as uuid)",Map.of("id",t.get("id")));return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("duplicate",false,"patient",row));}
 @GetMapping("/submissions") @PreAuthorize("hasAuthority('SELF_REGISTRATION_MANAGE')") public Map<String,Object> submissions(){GovCarePrincipal a=current.get();return Map.of("items",sql.list("select id::text,patient_no,full_name,nic,passport_no,phone,gender::text,status::text,created_at from patients where hospital_id=:hospital and status='pending' order by created_at desc",Map.of("hospital",a.hospitalId())));}
 @PostMapping("/submissions/{patientId}/approve") @PreAuthorize("hasAnyAuthority('SELF_REGISTRATION_MANAGE','PATIENT_UPDATE_DEMOGRAPHICS')") @Transactional public Map<String,Object> approve(@PathVariable String patientId){GovCarePrincipal a=current.get();return sql.required("update patients set status='active',updated_by=:user,updated_at=now() where id=cast(:id as uuid) and hospital_id=:hospital and status='pending' returning id::text,patient_no,full_name,nic,passport_no,phone,gender::text,status::text,created_at",map("user",a.id(),"id",patientId,"hospital",a.hospitalId()),"Pending registration was not found.");}
 private Map<String,Object> validToken(String token,boolean lock){return sql.required("select t.id::text,t.hospital_id::text,h.name hospital_name,h.city hospital_city,t.label,t.expires_at,t.uses_count,t.max_uses,t.status::text from patient_registration_tokens t join hospitals h on h.id=t.hospital_id where t.token_hash=:hash and t.status='active' and t.expires_at>now() and t.uses_count<t.max_uses"+(lock?" for update":""),Map.of("hash",hash(token)),"Registration QR code is invalid, expired, or fully used.");}
 private static String hash(String value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static List<String>split(Object o){String s=clean(o);if(s==null)return List.of();return Arrays.stream(s.split("[,;]" )).map(String::trim).filter(x->!x.isBlank()).toList();}private static String clean(Object o){if(o==null)return null;String s=String.valueOf(o).trim();return s.isBlank()?null:s;}private static String req(Map<String,Object>m,String k){String s=clean(m.get(k));if(s==null)throw ApiException.badRequest(k+" is required.");return s;}private static Map<String,Object>map(Object...x){Map<String,Object>m=new HashMap<>();for(int i=0;i<x.length;i+=2)m.put(String.valueOf(x[i]),x[i+1]);return m;}
}
