package lk.gov.health.govcare.pdf;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lk.gov.health.govcare.common.ApiException;
import lk.gov.health.govcare.common.SqlSupport;
import lk.gov.health.govcare.security.GovCarePrincipal;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
@Service public class PdfReportService{private final SqlSupport sql;public PdfReportService(SqlSupport sql){this.sql=sql;}
 public Report generate(GovCarePrincipal a,String kind,String id){Map<String,Object>h=hospital(a);return switch(kind){case"pharmacy"->prescription(a,id,h);case"laboratory"->laboratory(a,id,h);case"radiology"->radiology(a,id,h);case"consultations"->consultation(a,id,h);case"patients"->patient(a,id,h);default->throw ApiException.notFound("Unknown PDF report type.");};}
 private Report prescription(GovCarePrincipal a,String id,Map<String,Object>h){Map<String,Object>m=sql.required("select rx.id::text,rx.prescription_no,p.id::text patient_id,p.patient_no,p.full_name,govcare_patient_age_years(p.date_of_birth) age_years,p.gender::text,p.phone,p.blood_group,u.full_name doctor_name,rx.created_at consultation_date,rx.diagnosis,rx.pharmacy_status,rx.dispensed_at from prescriptions rx join patients p on p.id=rx.patient_id join app_users u on u.id=rx.doctor_id where rx.id=cast(:id as uuid) and rx.hospital_id=:hospital",Map.of("id",id,"hospital",a.hospitalId()),"Prescription not found.");own(a,m.get("patient_id"));List<Map<String,Object>>lines=sql.list("select medicine_name,strength,dosage,frequency,duration,quantity,instructions from prescription_items where prescription_id=cast(:id as uuid) order by created_at",Map.of("id",id));return report(h,"Pharmacy Prescription",m,List.of("prescription_no","patient_no","full_name","age_years","gender","phone","blood_group","doctor_name","consultation_date","diagnosis","pharmacy_status","dispensed_at"),lines,"prescription-"+m.get("prescription_no")+".pdf");}
 private Report laboratory(GovCarePrincipal a,String id,Map<String,Object>h){Map<String,Object>m=sql.required("select lr.id::text,lr.patient_id::text,p.patient_no,p.full_name,govcare_patient_age_years(p.date_of_birth) age_years,p.gender::text,p.phone,lr.test_type,lr.specimen,lr.priority::text,lr.clinical_reason,lr.created_at sample_date,u.full_name requested_by_name,r.numeric_result,r.text_result,r.unit,r.reference_range,r.classification,r.verified_at from lab_requests lr join patients p on p.id=lr.patient_id left join app_users u on u.id=lr.requested_by left join lateral(select * from lab_results where lab_request_id=lr.id order by created_at desc limit 1)r on true where lr.id=cast(:id as uuid) and lr.hospital_id=:hospital",Map.of("id",id,"hospital",a.hospitalId()),"Laboratory order not found.");own(a,m.get("patient_id"));List<Map<String,Object>>rows=List.of(map("parameter",m.get("test_type"),"result",m.get("numeric_result")!=null?m.get("numeric_result"):m.get("text_result"),"normal_range",m.get("reference_range"),"unit",m.get("unit")));return report(h,"Laboratory Report",m,List.of("patient_no","full_name","age_years","gender","phone","requested_by_name","test_type","specimen","priority","clinical_reason","sample_date","classification","verified_at"),rows,"laboratory-"+id+".pdf");}
 private Report radiology(GovCarePrincipal a,String id,Map<String,Object>h){Map<String,Object>m=sql.required("select rr.id::text,rr.patient_id::text,p.patient_no,p.full_name,govcare_patient_age_years(p.date_of_birth) age_years,p.gender::text,p.phone,rr.imaging_type,rr.body_area,rr.priority::text,rr.clinical_reason,rr.created_at investigation_date,u.full_name requested_by_name,rep.findings,rep.impression,rep.classification,rad.full_name radiologist_name,rep.verified_at from radiology_requests rr join patients p on p.id=rr.patient_id left join app_users u on u.id=rr.requested_by left join lateral(select * from radiology_reports where radiology_request_id=rr.id order by created_at desc limit 1)rep on true left join app_users rad on rad.id=rep.radiologist_id where rr.id=cast(:id as uuid) and rr.hospital_id=:hospital",Map.of("id",id,"hospital",a.hospitalId()),"Radiology request not found.");own(a,m.get("patient_id"));return report(h,"Radiology Report",m,List.of("patient_no","full_name","age_years","gender","phone","requested_by_name","imaging_type","body_area","priority","investigation_date","findings","impression","classification","radiologist_name","verified_at"),List.of(),"radiology-"+id+".pdf");}
 private Report consultation(GovCarePrincipal a,String id,Map<String,Object>h){Map<String,Object>m=sql.required("select c.id::text,c.patient_id::text,p.patient_no,p.full_name,govcare_patient_age_years(p.date_of_birth) age_years,p.gender::text,p.blood_group,v.visit_no,c.created_at consultation_date,u.full_name doctor_name,c.chief_complaint,c.presenting_history,c.examination,c.diagnosis,c.clinical_notes,c.treatment_plan,c.follow_up_instructions,c.follow_up_date from consultations c join patients p on p.id=c.patient_id join visits v on v.id=c.visit_id left join app_users u on u.id=c.doctor_id where c.id=cast(:id as uuid) and c.hospital_id=:hospital",Map.of("id",id,"hospital",a.hospitalId()),"Consultation not found.");own(a,m.get("patient_id"));List<Map<String,Object>>rx=sql.list("select prescription_no,diagnosis,pharmacy_status,created_at from prescriptions where consultation_id=cast(:id as uuid) order by created_at",Map.of("id",id));return report(h,"Doctor Consultation",m,List.of("patient_no","full_name","age_years","gender","blood_group","visit_no","consultation_date","doctor_name","chief_complaint","presenting_history","examination","diagnosis","clinical_notes","treatment_plan","follow_up_instructions","follow_up_date"),rx,"consultation-"+id+".pdf");}
 private Report patient(GovCarePrincipal a,String id,Map<String,Object>h){Map<String,Object>m=sql.required("select id::text patient_id,patient_no,full_name,nic,passport_no,birth_certificate_no,date_of_birth,govcare_patient_age_years(date_of_birth) age_years,gender::text,blood_group,phone,email,address,district,province,allergies,chronic_diseases,created_at from patients where hospital_id=:hospital and(id::text=:id or patient_no=:id or nic=:id) and status<>'deleted' limit 1",Map.of("id",id,"hospital",a.hospitalId()),"Patient not found.");own(a,m.get("patient_id"));List<String>fields=new ArrayList<>(List.of("patient_no","full_name","nic","passport_no","birth_certificate_no","date_of_birth","age_years","gender","blood_group","phone","email","address","district","province","created_at"));if(a.permissions().contains("PATIENT_VIEW_CLINICAL")){fields.add("allergies");fields.add("chronic_diseases");}List<Map<String,Object>>history=sql.list("select v.visit_no,v.visit_type,v.reason,v.diagnosis_summary,v.created_at from visits v where v.patient_id=cast(:patient as uuid) and v.hospital_id=:hospital order by v.created_at desc limit 50",Map.of("patient",m.get("patient_id"),"hospital",a.hospitalId()));return report(h,"Patient Details",m,fields,history,"patient-"+m.get("patient_no")+".pdf");}
 private Report report(Map<String,Object>hospital,String title,Map<String,Object>main,List<String>fields,List<Map<String,Object>>rows,String filename){try{ByteArrayOutputStream out=new ByteArrayOutputStream();Document doc=new Document(PageSize.A4,36,36,42,42);PdfWriter.getInstance(doc,out);doc.open();Font heading=new Font(Font.HELVETICA,18,Font.BOLD,new Color(15,74,110));Font sub=new Font(Font.HELVETICA,11,Font.BOLD);doc.add(new Paragraph(Objects.toString(hospital.get("name"),"GovCare Hospital"),heading));doc.add(new Paragraph(title,new Font(Font.HELVETICA,15,Font.BOLD)));doc.add(new Paragraph("Generated by GovCare EHR",new Font(Font.HELVETICA,8,Font.ITALIC)));doc.add(Chunk.NEWLINE);PdfPTable details=new PdfPTable(2);details.setWidthPercentage(100);for(String f:fields){details.addCell(cell(label(f),true));details.addCell(cell(Objects.toString(main.get(f),"Not recorded"),false));}doc.add(details);if(!rows.isEmpty()){doc.add(Chunk.NEWLINE);doc.add(new Paragraph("Related Records",sub));Set<String>cols=new LinkedHashSet<>();rows.forEach(r->cols.addAll(r.keySet()));PdfPTable t=new PdfPTable(cols.size());t.setWidthPercentage(100);for(String c:cols)t.addCell(cell(label(c),true));for(Map<String,Object>r:rows)for(String c:cols)t.addCell(cell(Objects.toString(r.get(c),""),false));doc.add(t);}doc.add(Chunk.NEWLINE);doc.add(new Paragraph("Authorized signature: ______________________________",new Font(Font.HELVETICA,10)));doc.close();return new Report(out.toByteArray(),filename);}catch(Exception e){throw new IllegalStateException("Unable to generate PDF report.",e);}}
 private Map<String,Object>hospital(GovCarePrincipal a){return sql.required("select name,code,address,phone,email from hospitals where id=:id",Map.of("id",a.hospitalId()),"Hospital not found.");}private void own(GovCarePrincipal a,Object patient){if(Set.of("patient","guardian").contains(a.role())&&(a.patientId()==null||!Objects.equals(a.patientId().toString(),String.valueOf(patient))))throw ApiException.forbidden("Patients can only download their own records.");}private static PdfPCell cell(String text,boolean head){PdfPCell c=new PdfPCell(new Phrase(text,new Font(Font.HELVETICA,head?8:8,head?Font.BOLD:Font.NORMAL)));c.setPadding(5);if(head)c.setBackgroundColor(new Color(225,240,245));return c;}private static String label(String x){String s=x.replace('_',' ');return Character.toUpperCase(s.charAt(0))+s.substring(1);}private static Map<String,Object>map(Object...x){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<x.length;i+=2)m.put(String.valueOf(x[i]),x[i+1]);return m;}public record Report(byte[]bytes,String filename){}
}
