package lk.gov.health.govcare.workflow;

import lk.gov.health.govcare.audit.AuditService;
import lk.gov.health.govcare.common.ApiException;
import lk.gov.health.govcare.common.JsonSupport;
import lk.gov.health.govcare.common.SqlSupport;
import lk.gov.health.govcare.security.GovCarePrincipal;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;

@Service
public class ConsultationService {
    private final SqlSupport sql;private final JsonSupport json;private final AuditService audit;
    public ConsultationService(SqlSupport sql,JsonSupport json,AuditService audit){this.sql=sql;this.json=json;this.audit=audit;}
    public static final String SELECT="""
      select c.id::text,c.hospital_id::text,c.patient_id::text,c.visit_id::text,c.doctor_id::text,c.chief_complaint,c.symptoms,c.history,c.presenting_history,
      c.past_medical_history,c.surgical_history,c.family_history,c.social_history,c.allergy_review,c.current_medications,c.vital_signs,c.examination,c.diagnosis,
      c.differential_diagnosis,c.icd10_code,c.soap_notes,c.clinical_notes,c.treatment_plan,c.follow_up_instructions,c.follow_up_date,c.workflow_status,c.started_at,
      c.completed_at,c.completion_override_reason,c.status::text,c.created_at,c.updated_at,p.patient_no,p.full_name as patient_name,u.full_name as doctor_name,v.visit_no
      from consultations c join patients p on p.id=c.patient_id join visits v on v.id=c.visit_id join app_users u on u.id=c.doctor_id
      """;

    public List<Map<String,Object>> patient(GovCarePrincipal a,String id){return sql.list(SELECT+" where c.patient_id=cast(:id as uuid) and c.hospital_id=:hospital order by c.created_at desc",Map.of("id",id,"hospital",a.hospitalId()));}
    public Map<String,Object> byVisit(GovCarePrincipal a,String id){return sql.required(SELECT+" where c.visit_id=cast(:id as uuid) and c.hospital_id=:hospital order by c.created_at desc limit 1",Map.of("id",id,"hospital",a.hospitalId()),"Consultation not found for this visit.");}
    public Map<String,Object> get(GovCarePrincipal a,String id){return sql.required(SELECT+" where c.id=cast(:id as uuid) and c.hospital_id=:hospital limit 1",Map.of("id",id,"hospital",a.hospitalId()),"Consultation not found.");}

    @Transactional
    public Map<String,Object> create(GovCarePrincipal a,Map<String,Object> input){String patient=req(input,"patientUuid"),visit=req(input,"visitUuid");if(sql.one("select id from visits where id=cast(:visit as uuid) and patient_id=cast(:patient as uuid) and hospital_id=:hospital",map("visit",visit,"patient",patient,"hospital",a.hospitalId())).isEmpty())throw ApiException.notFound("The selected patient and visit are not linked in PostgreSQL.");String existing=sql.one("select id::text from consultations where visit_id=cast(:visit as uuid) and patient_id=cast(:patient as uuid) and hospital_id=:hospital order by created_at desc limit 1",map("visit",visit,"patient",patient,"hospital",a.hospitalId())).map(r->String.valueOf(r.get("id"))).orElse(null);return persist(a,existing,patient,visit,input);}

    @Transactional
    public Map<String,Object> update(GovCarePrincipal a,String id,Map<String,Object> input,boolean complete){Map<String,Object>existing=get(a,id);String patient=String.valueOf(existing.get("patient_id")),visit=String.valueOf(existing.get("visit_id"));Map<String,Object>merged=new HashMap<>();String[] camel={"chiefComplaint","symptoms","history","presentingHistory","pastMedicalHistory","surgicalHistory","familyHistory","socialHistory","allergyReview","currentMedications","vitalSigns","examination","diagnosis","differentialDiagnosis","icd10Code","soapNotes","clinicalNotes","treatmentPlan","followUpInstructions","followUpDate","completionOverrideReason","queueUuid"};String[] snake={"chief_complaint","symptoms","history","presenting_history","past_medical_history","surgical_history","family_history","social_history","allergy_review","current_medications","vital_signs","examination","diagnosis","differential_diagnosis","icd10_code","soap_notes","clinical_notes","treatment_plan","follow_up_instructions","follow_up_date","completion_override_reason","queue_uuid"};for(int i=0;i<camel.length;i++)merged.put(camel[i],input.containsKey(camel[i])?input.get(camel[i]):existing.get(snake[i]));merged.put("workflowStatus",complete?"completed":input.getOrDefault("workflowStatus",existing.get("workflow_status")));if(complete){Number unresolved=(Number)sql.required("select ((select count(*) from lab_requests where consultation_id=cast(:id as uuid) and hospital_id=:hospital and priority in ('urgent','stat','critical') and workflow_status not in ('released','reviewed','cancelled'))+(select count(*) from radiology_requests where consultation_id=cast(:id as uuid) and hospital_id=:hospital and priority in ('urgent','stat','critical') and workflow_status not in ('released','reviewed','cancelled')))::int total",Map.of("id",id,"hospital",a.hospitalId()),"Unable to check pending orders.").get("total");if(unresolved.intValue()>0&&clean(merged.get("completionOverrideReason"))==null)throw ApiException.conflict("Urgent laboratory or radiology orders are unresolved. Provide an override reason to complete this consultation.");}return persist(a,id,patient,visit,merged);}

    private Map<String,Object> persist(GovCarePrincipal a,String id,String patient,String visit,Map<String,Object> in){String workflow=String.valueOf(in.getOrDefault("workflowStatus","draft"));if(!Set.of("draft","active","awaiting_results","ready_for_review","completed","cancelled").contains(workflow))throw ApiException.badRequest("Invalid consultation workflow status.");String record=workflow.equals("completed")?"completed":workflow.equals("cancelled")?"cancelled":"active";Map<String,Object>p=new HashMap<>();p.put("hospital",a.hospitalId());p.put("patient",patient);p.put("visit",visit);p.put("doctor",a.id());p.put("workflow",workflow);p.put("record",record);p.put("chief",clean(in.get("chiefComplaint")));p.put("symptoms",clean(in.get("symptoms")));p.put("history",clean(in.get("history")));p.put("presenting",clean(in.get("presentingHistory")));p.put("past",clean(in.get("pastMedicalHistory")));p.put("surgical",clean(in.get("surgicalHistory")));p.put("family",clean(in.get("familyHistory")));p.put("social",clean(in.get("socialHistory")));p.put("allergy",clean(in.get("allergyReview")));p.put("medications",clean(in.get("currentMedications")));p.put("vitals",json.write(in.getOrDefault("vitalSigns",Map.of())));p.put("examination",clean(in.get("examination")));p.put("diagnosis",clean(in.get("diagnosis")));p.put("differential",clean(in.get("differentialDiagnosis")));p.put("icd",clean(in.get("icd10Code")));p.put("soap",json.write(in.getOrDefault("soapNotes",Map.of())));p.put("clinical",clean(in.get("clinicalNotes")));p.put("plan",clean(in.get("treatmentPlan")));p.put("follow",clean(in.get("followUpInstructions")));p.put("followDate",clean(in.get("followUpDate")));p.put("override",clean(in.get("completionOverrideReason")));
        if(id==null){Map<String,Object>r=sql.required("""
          insert into consultations(hospital_id,patient_id,visit_id,doctor_id,chief_complaint,symptoms,history,presenting_history,past_medical_history,surgical_history,family_history,social_history,allergy_review,current_medications,vital_signs,examination,diagnosis,differential_diagnosis,icd10_code,soap_notes,clinical_notes,treatment_plan,follow_up_instructions,follow_up_date,workflow_status,started_at,completed_at,completion_override_reason,release_status,status,created_by,updated_by)
          values(:hospital,cast(:patient as uuid),cast(:visit as uuid),:doctor,:chief,:symptoms,:history,:presenting,:past,:surgical,:family,:social,:allergy,:medications,cast(:vitals as jsonb),:examination,:diagnosis,:differential,:icd,cast(:soap as jsonb),:clinical,:plan,:follow,cast(:followDate as date),:workflow,now(),case when :workflow='completed' then now() else null end,:override,'internal',cast(:record as record_status),:doctor,:doctor) returning id::text
        """,p,"Unable to create consultation.");id=String.valueOf(r.get("id"));}else{p.put("id",id);sql.update("""
          update consultations set chief_complaint=:chief,symptoms=:symptoms,history=:history,presenting_history=:presenting,past_medical_history=:past,surgical_history=:surgical,family_history=:family,social_history=:social,allergy_review=:allergy,current_medications=:medications,vital_signs=cast(:vitals as jsonb),examination=:examination,diagnosis=:diagnosis,differential_diagnosis=:differential,icd10_code=:icd,soap_notes=cast(:soap as jsonb),clinical_notes=:clinical,treatment_plan=:plan,follow_up_instructions=:follow,follow_up_date=cast(:followDate as date),workflow_status=:workflow,completion_override_reason=:override,doctor_id=:doctor,started_at=coalesce(started_at,now()),completed_at=case when :workflow='completed' then now() else completed_at end,status=cast(:record as record_status),updated_by=:doctor where id=cast(:id as uuid) and hospital_id=:hospital
        """,p);}if(clean(in.get("diagnosis"))!=null){sql.update("delete from consultation_diagnoses where consultation_id=cast(:id as uuid) and diagnosis_type='primary'",Map.of("id",id));sql.update("insert into consultation_diagnoses(hospital_id,consultation_id,patient_id,code,description,diagnosis_type,created_by) values(:hospital,cast(:id as uuid),cast(:patient as uuid),:icd,:diagnosis,'primary',:doctor)",map("hospital",a.hospitalId(),"id",id,"patient",patient,"icd",clean(in.get("icd10Code")),"diagnosis",clean(in.get("diagnosis")),"doctor",a.id()));}if(workflow.equals("completed")){sql.update("update visits set workflow_status='completed',status='completed',completed_at=now(),diagnosis_summary=:diagnosis,updated_by=:doctor where id=cast(:visit as uuid) and hospital_id=:hospital",map("diagnosis",clean(in.get("diagnosis")),"doctor",a.id(),"visit",visit,"hospital",a.hospitalId()));String queue=clean(in.get("queueUuid"));if(queue!=null)sql.update("update opd_queue set queue_status='completed',completed_at=now(),updated_by=:doctor,version=version+1 where id=cast(:queue as uuid) and hospital_id=:hospital and patient_id=cast(:patient as uuid)",map("doctor",a.id(),"queue",queue,"hospital",a.hospitalId(),"patient",patient));else sql.update("update opd_queue set queue_status='completed',completed_at=now(),updated_by=:doctor,version=version+1 where visit_id=cast(:visit as uuid) and hospital_id=:hospital and patient_id=cast(:patient as uuid) and queue_status in ('checking','in-consultation')",map("doctor",a.id(),"visit",visit,"hospital",a.hospitalId(),"patient",patient));}Map<String,Object>out=get(a,id);audit.record(a,"consultations",workflow.equals("completed")?"consultation_completed":"consultation_saved","consultations",UUID.fromString(id),null,out);return out;}
    private static String clean(Object o){if(o==null)return null;String s=String.valueOf(o).trim();return s.isEmpty()||s.equals("null")?null:s;}private static String req(Map<String,Object>m,String k){String s=clean(m.get(k));if(s==null)throw ApiException.badRequest(k+" is required.");return s;}private static Map<String,Object>map(Object...v){Map<String,Object>m=new HashMap<>();for(int i=0;i<v.length;i+=2)m.put(String.valueOf(v[i]),v[i+1]);return m;}
}
