package lk.gov.health.govcare.workflow;

import lk.gov.health.govcare.audit.AuditService;
import lk.gov.health.govcare.common.ApiException;
import lk.gov.health.govcare.common.SequenceService;
import lk.gov.health.govcare.common.SqlSupport;
import lk.gov.health.govcare.security.GovCarePrincipal;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.*;

@Service
public class QueueService {
    private final SqlSupport sql;private final WorkflowSql workflow;private final SequenceService sequences;private final AuditService audit;
    public QueueService(SqlSupport sql,WorkflowSql workflow,SequenceService sequences,AuditService audit){this.sql=sql;this.workflow=workflow;this.sequences=sequences;this.audit=audit;}

    public List<Map<String,Object>> list(GovCarePrincipal actor,String status){StringBuilder q=new StringBuilder(WorkflowSql.QUEUE_SELECT+" where q.hospital_id=:hospitalId");Map<String,Object> p=new HashMap<>();p.put("hospitalId",actor.hospitalId());if(clean(status)!=null){q.append(" and q.queue_status=:status");p.put("status",status.trim());}else q.append(" and (q.queue_status in ('waiting','called','checking','in-consultation','paused') or (q.queue_status in ('completed','no_show') and q.updated_at::date=current_date))");if(actor.role().equals("doctor")){q.append(" and (q.doctor_id is null or q.doctor_id=:doctorId or (:departmentId is not null and q.department_id=:departmentId))");p.put("doctorId",actor.id());p.put("departmentId",actor.departmentId());}q.append(" order by case q.queue_status when 'checking' then 0 when 'called' then 1 when 'waiting' then 2 else 3 end,case q.priority when 'critical' then 1 when 'stat' then 1 when 'urgent' then 2 else 3 end,q.created_at asc limit 250");return sql.list(q.toString(),p);}

    @Transactional
    public Map<String,Object> create(GovCarePrincipal actor,Map<String,Object> input){String identifier=req(input,"identifier"),reason=req(input,"reason");Map<String,Object> patient=workflow.patient(actor.hospitalId(),identifier);if(patient==null)throw ApiException.notFound("Patient was not found in this hospital.");Map<String,Object> department=workflow.department(actor.hospitalId(),clean(input.get("departmentUuid")),clean(input.get("departmentName")));if(department==null)throw ApiException.notFound("Department was not found in this hospital.");String doctor=clean(input.get("doctorUuid"));workflow.requireDoctor(actor.hospitalId(),doctor);String appointment=clean(input.get("appointmentUuid"));if(appointment!=null){Map<String,Object>a=sql.required("select patient_id::text from appointments where id=cast(:id as uuid) and hospital_id=:hospitalId",Map.of("id",appointment,"hospitalId",actor.hospitalId()),"Appointment not found.");if(!Objects.equals(String.valueOf(a.get("patient_id")),String.valueOf(patient.get("id"))))throw ApiException.conflict("The appointment does not belong to the selected patient.");}
        sequences.lock("govcare:"+actor.hospitalId()+":queue:"+OffsetDateTime.now().toLocalDate());Number count=(Number)sql.required("select count(*)::int total from opd_queue where hospital_id=:hospitalId and created_at::date=current_date",Map.of("hospitalId",actor.hospitalId()),"Unable to generate token.").get("total");int seq=count.intValue()+1;String token=WorkflowSql.tokenPrefix(String.valueOf(department.get("name")),String.valueOf(department.get("code")))+"-"+String.format("%03d",seq);String visitNo=sequences.daily(actor.hospitalId(),"visits","visit_no","VIS-");Map<String,Object>p=new HashMap<>();p.put("hospitalId",actor.hospitalId());p.put("patientId",patient.get("id"));p.put("departmentId",department.get("id"));p.put("doctorId",doctor);p.put("appointmentId",appointment);p.put("visitNo",visitNo);p.put("visitType",String.valueOf(input.getOrDefault("visitType",appointment==null?"walk-in":"appointment")));p.put("reason",reason);p.put("priority",String.valueOf(input.getOrDefault("priority","routine")));p.put("actorId",actor.id());p.put("token",token);
        Map<String,Object>visit=sql.required("""
          insert into visits(hospital_id,patient_id,department_id,doctor_id,appointment_id,visit_no,visit_type,reason,priority,workflow_status,status,created_by,updated_by)
          values(:hospitalId,cast(:patientId as uuid),cast(:departmentId as uuid),cast(:doctorId as uuid),cast(:appointmentId as uuid),:visitNo,:visitType,:reason,cast(:priority as priority_level),'waiting','pending',:actorId,:actorId) returning id::text
        """,p,"Unable to create visit.");p.put("visitId",visit.get("id"));Map<String,Object>queue=sql.required("""
          insert into opd_queue(hospital_id,visit_id,patient_id,department_id,doctor_id,appointment_id,token_no,queue_status,priority,estimated_wait_minutes,created_by,updated_by)
          values(:hospitalId,cast(:visitId as uuid),cast(:patientId as uuid),cast(:departmentId as uuid),cast(:doctorId as uuid),cast(:appointmentId as uuid),:token,'waiting',cast(:priority as priority_level),0,:actorId,:actorId) returning id::text
        """,p,"Unable to create queue.");if(appointment!=null)sql.update("update appointments set queue_id=cast(:queueId as uuid),checked_in_at=coalesce(checked_in_at,now()),workflow_status='waiting',updated_by=:actorId where id=cast(:appointmentId as uuid)",Map.of("queueId",queue.get("id"),"actorId",actor.id(),"appointmentId",appointment));audit.record(actor,"opd","queue_created","opd_queue",UUID.fromString(String.valueOf(queue.get("id"))),null,queue);return workflow.queue(actor.hospitalId(),String.valueOf(queue.get("id")));}

    @Transactional
    public Map<String,Object> assign(GovCarePrincipal actor,String id,Map<String,Object> input){String doctor=clean(input.get("doctorUuid"));workflow.requireDoctor(actor.hospitalId(),doctor);int n=sql.update("update opd_queue set doctor_id=cast(:doctor as uuid),updated_by=:actor,version=version+1 where id=cast(:id as uuid) and hospital_id=:hospital",map("doctor",doctor,"actor",actor.id(),"id",id,"hospital",actor.hospitalId()));if(n==0)throw ApiException.notFound("Queue record not found.");sql.update("update visits set doctor_id=cast(:doctor as uuid),updated_by=:actor where id=(select visit_id from opd_queue where id=cast(:id as uuid))",map("doctor",doctor,"actor",actor.id(),"id",id));return workflow.queue(actor.hospitalId(),id);}

    @Transactional
    public Map<String,Object> transition(GovCarePrincipal actor,String id,String action){Map<String,String>to=Map.of("call","called","recall","called","no-show","no_show","return-waiting","waiting","complete","completed");String target=to.get(action);if(target==null)throw ApiException.badRequest("Unsupported queue action.");Map<String,Object>row=sql.required("select id::text,queue_status,patient_id::text,visit_id::text,doctor_id::text,department_id::text,appointment_id::text from opd_queue where id=cast(:id as uuid) and hospital_id=:hospital for update",Map.of("id",id,"hospital",actor.hospitalId()),"Queue record not found.");Set<String>allowed=switch(action){case"call"->Set.of("waiting","paused");case"recall"->Set.of("called","no_show");case"no-show"->Set.of("waiting","called");case"return-waiting"->Set.of("called","no_show","paused");case"complete"->Set.of("checking","in-consultation");default->Set.of();};if(!allowed.contains(String.valueOf(row.get("queue_status"))))throw ApiException.conflict("Cannot "+action+" while queue status is "+row.get("queue_status")+".");checkDoctor(actor,row);Map<String,Object>p=map("id",id,"hospital",actor.hospitalId(),"actor",actor.id(),"target",target);sql.update("""
          update opd_queue set queue_status=:target,called_at=case when :target='called' then now() else called_at end,called_by=case when :target='called' then :actor else called_by end,
          no_show_at=case when :target='no_show' then now() when :target='waiting' then null else no_show_at end,paused_at=case when :target='waiting' then null else paused_at end,
          completed_at=case when :target='completed' then now() else completed_at end,updated_by=:actor,version=version+1 where id=cast(:id as uuid) and hospital_id=:hospital
        """,p);String visitStatus=target.equals("completed")?"completed":target.equals("no_show")?"cancelled":"pending";sql.update("update visits set workflow_status=:target,status=cast(:status as record_status),completed_at=case when :target='completed' then now() else completed_at end,updated_by=:actor where id=cast(:visit as uuid)",map("target",target,"status",visitStatus,"actor",actor.id(),"visit",row.get("visit_id")));return workflow.queue(actor.hospitalId(),id);}

    @Transactional
    public Map<String,Object> start(GovCarePrincipal actor,String id){Map<String,Object>row=sql.required("select id::text,queue_status,patient_id::text,visit_id::text,doctor_id::text,department_id::text,appointment_id::text from opd_queue where id=cast(:id as uuid) and hospital_id=:hospital for update",Map.of("id",id,"hospital",actor.hospitalId()),"Queue record not found.");checkDoctor(actor,row);if(!Set.of("waiting","called","checking","in-consultation").contains(String.valueOf(row.get("queue_status"))))throw ApiException.conflict("Queue cannot be started while status is "+row.get("queue_status"));sql.update("update opd_queue set queue_status='checking',doctor_id=coalesce(doctor_id,:doctor),called_at=coalesce(called_at,now()),called_by=coalesce(called_by,:doctor),started_at=coalesce(started_at,now()),updated_by=:doctor,version=version+1 where id=cast(:id as uuid)",Map.of("doctor",actor.id(),"id",id));sql.update("update visits set doctor_id=:doctor,checked_at=coalesce(checked_at,now()),workflow_status='checking',status='active',updated_by=:doctor where id=cast(:visit as uuid)",Map.of("doctor",actor.id(),"visit",row.get("visit_id")));String consultation=sql.one("select id::text from consultations where hospital_id=:hospital and visit_id=cast(:visit as uuid) and patient_id=cast(:patient as uuid) order by created_at desc limit 1",map("hospital",actor.hospitalId(),"visit",row.get("visit_id"),"patient",row.get("patient_id"))).map(r->String.valueOf(r.get("id"))).orElse(null);if(consultation==null){Map<String,Object>created=sql.required("insert into consultations(hospital_id,patient_id,visit_id,doctor_id,workflow_status,started_at,status,created_by,updated_by) values(:hospital,cast(:patient as uuid),cast(:visit as uuid),:doctor,'active',now(),'active',:doctor,:doctor) returning id::text",map("hospital",actor.hospitalId(),"patient",row.get("patient_id"),"visit",row.get("visit_id"),"doctor",actor.id()),"Unable to start consultation.");consultation=String.valueOf(created.get("id"));}return Map.of("queue",workflow.queue(actor.hospitalId(),id),"consultationId",consultation);}

    private void checkDoctor(GovCarePrincipal a,Map<String,Object>r){if(!a.role().equals("doctor"))return;String doctor=clean(r.get("doctor_id")),department=clean(r.get("department_id"));if(doctor!=null&&!doctor.equals(a.id().toString())&&(a.departmentId()==null||!Objects.equals(department,a.departmentId().toString())))throw ApiException.forbidden("This queue patient is assigned to another doctor or department.");}
    private static String clean(Object o){if(o==null)return null;String s=String.valueOf(o).trim();return s.isEmpty()?null:s;}private static String req(Map<String,Object>m,String k){String s=clean(m.get(k));if(s==null)throw ApiException.badRequest(k+" is required.");return s;}private static Map<String,Object> map(Object...v){Map<String,Object>m=new HashMap<>();for(int i=0;i<v.length;i+=2)m.put(String.valueOf(v[i]),v[i+1]);return m;}
}
