import { Activity, Ambulance, BarChart3, BedDouble, CalendarClock, CalendarDays, ClipboardList, FileCheck2, FileClock, FileImage, FlaskConical, HeartPulse, Hospital, LayoutDashboard, LogIn, MessageSquareText, Pill, Radio, ScanBarcode, Scissors, Settings, ShieldCheck, Sparkles, Stethoscope, UserCircle, UserPlus, UserRoundCog, UsersRound } from "lucide-react";
import type { Role } from "../../types/ehr";

export const navItems: Array<{ href: string; label: string; translationKey: string; icon: typeof LayoutDashboard; roles: Role[] }> = [
  { href: "/super-admin", label: "Super Admin", translationKey: "nav.superAdmin", icon: ShieldCheck, roles: ["super_admin"] },
  { href: "/efficiency", label: "Efficiency Center", translationKey: "nav.efficiencyCenter", icon: Sparkles, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "pharmacist", "pathologist", "lab_manager", "lab_technician", "radiologist", "radiology_technician", "receptionist", "ict_admin", "records_officer"] },
  { href: "/", label: "Dashboard", translationKey: "nav.dashboard", icon: LayoutDashboard, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "pharmacist", "pathologist", "lab_manager", "lab_technician", "radiologist", "radiology_technician", "receptionist", "mortuary_officer", "ict_admin", "records_officer"] },
  { href: "/portal", label: "My Health", translationKey: "nav.myHealth", icon: UserCircle, roles: ["patient"] },
  { href: "/portal/appointments", label: "My Appointments", translationKey: "nav.myAppointments", icon: CalendarDays, roles: ["patient"] },
  { href: "/portal/messages", label: "Care Messages", translationKey: "nav.careMessages", icon: MessageSquareText, roles: ["doctor", "nurse", "patient"] },
  { href: "/portal/care-summary", label: "Care Summary", translationKey: "nav.careSummary", icon: HeartPulse, roles: ["doctor", "nurse", "patient"] },
  { href: "/portal/reports", label: "My Reports", translationKey: "nav.myReports", icon: BarChart3, roles: ["patient"] },
  { href: "/portal/medical-reports", label: "Official Medical Reports", translationKey: "nav.officialMedicalReports", icon: FileCheck2, roles: ["patient"] },
  { href: "/media", label: "Media Center", translationKey: "nav.mediaCenter", icon: FileImage, roles: ["super_admin", "hospital_admin", "doctor", "surgeon", "anesthetist", "nurse", "pharmacist", "pathologist", "lab_manager", "lab_technician", "radiologist", "radiology_technician", "receptionist", "mortuary_officer", "ict_admin", "records_officer", "patient"] },
  { href: "/profile", label: "Profile", translationKey: "nav.profile", icon: UserCircle, roles: ["doctor", "nurse", "patient"] },
  { href: "/doctor", label: "Doctor Center", translationKey: "nav.doctorCenter", icon: Stethoscope, roles: ["super_admin", "hospital_admin", "doctor"] },
  { href: "/doctor/workspace", label: "Consult Workspace", translationKey: "nav.consultWorkspace", icon: Activity, roles: ["super_admin", "hospital_admin", "doctor"] },
  { href: "/doctor/documents", label: "Doctor Documents", translationKey: "nav.departmentDocuments", icon: FileCheck2, roles: ["doctor", "surgeon", "anesthetist"] },
  { href: "/patients/register", label: "Patient Registration", translationKey: "nav.patientRegistration", icon: UserPlus, roles: ["super_admin", "hospital_admin", "receptionist", "records_officer"] },
  { href: "/admin/patient-fields", label: "Patient Field Policy", translationKey: "nav.patientFieldPolicy", icon: Settings, roles: ["super_admin", "hospital_admin", "ict_admin"] },
  { href: "/patients/search", label: "Patient Search", translationKey: "nav.patientSearch", icon: ScanBarcode, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist", "records_officer"] },
  { href: "/guardians", label: "Guardian Management", translationKey: "nav.guardianManagement", icon: UsersRound, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist", "records_officer", "patient"] },
  { href: "/patients/PAT-2026-0001", label: "Patient Profile", translationKey: "nav.patientProfile", icon: UsersRound, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "records_officer"] },
  { href: "/opd", label: "OPD Queue", translationKey: "nav.opdQueue", icon: ClipboardList, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist"] },
  { href: "/consultation", label: "Doctor Consultation", translationKey: "nav.doctorConsultation", icon: Activity, roles: ["super_admin", "hospital_admin", "doctor"] },
  { href: "/nurse-notes", label: "Nurse Module", translationKey: "nav.nurseModule", icon: ClipboardList, roles: ["super_admin", "hospital_admin", "nurse"] },
  { href: "/admissions", label: "Admissions", translationKey: "nav.admissions", icon: Hospital, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist", "records_officer"] },
  { href: "/wards", label: "Ward Management", translationKey: "nav.wardManagement", icon: BedDouble, roles: ["super_admin", "hospital_admin", "doctor", "nurse"] },
  { href: "/ward/documents", label: "Ward Documents", translationKey: "nav.departmentDocuments", icon: FileCheck2, roles: ["doctor", "surgeon", "nurse"] },
  { href: "/operation-theatre", label: "Operation Theatre", translationKey: "nav.operationTheatre", icon: Scissors, roles: ["super_admin", "hospital_admin", "doctor", "surgeon", "anesthetist", "nurse"] },
  { href: "/future-care", label: "Future Care", translationKey: "nav.futureCare", icon: CalendarClock, roles: ["super_admin", "hospital_admin", "doctor", "surgeon", "nurse", "records_officer"] },
  { href: "/pharmacy", label: "Pharmacy", translationKey: "nav.pharmacy", icon: Pill, roles: ["super_admin", "hospital_admin", "doctor", "pharmacist"] },
  { href: "/pharmacy/documents", label: "Pharmacy Documents", translationKey: "nav.departmentDocuments", icon: FileCheck2, roles: ["pharmacist"] },
  { href: "/e-prescription", label: "E-Prescription", translationKey: "nav.ePrescription", icon: Pill, roles: ["super_admin", "hospital_admin", "doctor"] },
  { href: "/laboratory", label: "Laboratory", translationKey: "nav.laboratory", icon: FlaskConical, roles: ["super_admin", "hospital_admin", "pathologist", "lab_manager", "lab_technician", "doctor", "nurse"] },
  { href: "/laboratory/documents", label: "Laboratory Documents", translationKey: "nav.departmentDocuments", icon: FileCheck2, roles: ["pathologist", "lab_manager", "lab_technician"] },
  { href: "/radiology", label: "Radiology", translationKey: "nav.radiology", icon: Radio, roles: ["super_admin", "hospital_admin", "radiologist", "radiology_technician", "doctor", "nurse"] },
  { href: "/radiology/documents", label: "Radiology Documents", translationKey: "nav.departmentDocuments", icon: FileCheck2, roles: ["radiologist", "radiology_technician"] },
  { href: "/emergency", label: "Emergency", translationKey: "nav.emergency", icon: Ambulance, roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist"] },
  { href: "/mortuary", label: "Mortuary", translationKey: "nav.mortuary", icon: FileClock, roles: ["super_admin", "hospital_admin", "doctor", "mortuary_officer", "records_officer"] },
  { href: "/appointments", label: "Appointments", translationKey: "nav.appointments", icon: CalendarDays, roles: ["super_admin", "hospital_admin", "doctor", "receptionist"] },
  { href: "/reports", label: "Reports", translationKey: "nav.reports", icon: BarChart3, roles: ["super_admin", "hospital_admin", "records_officer", "ict_admin", "receptionist", "doctor", "nurse", "pharmacist", "pathologist", "lab_manager", "lab_technician", "radiologist", "radiology_technician"] },
  { href: "/medical-report-review", label: "Medical Report Review", translationKey: "nav.medicalReportReview", icon: FileCheck2, roles: ["super_admin", "hospital_admin", "doctor", "records_officer"] },
  { href: "/notifications", label: "Notifications", translationKey: "nav.notifications", icon: Activity, roles: ["super_admin", "hospital_admin", "doctor", "surgeon", "anesthetist", "nurse", "pharmacist", "pathologist", "lab_manager", "lab_technician", "radiologist", "radiology_technician", "receptionist", "ict_admin", "records_officer", "patient"] },
  { href: "/admin/staff", label: "Staff Management", translationKey: "nav.staffManagement", icon: UserRoundCog, roles: ["super_admin", "hospital_admin"] },
  { href: "/audit-logs", label: "Audit Logs", translationKey: "nav.auditLogs", icon: FileClock, roles: ["super_admin", "hospital_admin", "ict_admin", "records_officer"] },
  { href: "/admin/login-activity", label: "Login Activity", translationKey: "nav.loginActivity", icon: LogIn, roles: ["super_admin", "hospital_admin", "ict_admin"] },
  { href: "/settings", label: "Settings", translationKey: "nav.settings", icon: Settings, roles: ["super_admin", "hospital_admin", "ict_admin"] },
];
