import type { Role } from "../types/ehr";

export type NotificationPriority = "information" | "warning" | "urgent" | "critical";
export type NotificationChannel = "in-app" | "push" | "email" | "sms" | "sound";

export interface GovCareNotification {
  id: string;
  title: string;
  message: string;
  module: string;
  priority: NotificationPriority;
  roles: Role[];
  channels: NotificationChannel[];
  timestamp: string;
  read: boolean;
  archived: boolean;
  group: string;
  actionHref?: string;
}

const STORAGE_KEY = "govcare-notifications";
export const NOTIFICATIONS_UPDATED_EVENT = "govcare:notifications-updated";
export const NOTIFICATION_POPUP_EVENT = "govcare:notification-popup";

const allStaff: Role[] = ["super_admin", "hospital_admin", "doctor", "nurse", "pharmacist", "pathologist", "lab_manager", "lab_technician", "radiologist", "radiology_technician", "receptionist", "records_officer"];
const clinical: Role[] = ["super_admin", "hospital_admin", "doctor", "nurse"];

export const seedNotifications: GovCareNotification[] = [
  { id: "n-001", title: "Critical lab finding", message: "Troponin I is critically elevated for R. Kumar. Doctor review required now.", module: "Laboratory", priority: "critical", roles: ["super_admin", "hospital_admin", "doctor", "nurse", "pathologist", "lab_manager", "lab_technician"], channels: ["in-app", "push", "sound"], timestamp: "2026-06-14T08:35:00+05:30", read: false, archived: false, group: "Diagnostics", actionHref: "/laboratory" },
  { id: "n-002", title: "Emergency case arrived", message: "ETU registered a chest pain case with emergency-priority queue status.", module: "Emergency Department", priority: "critical", roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist"], channels: ["in-app", "push", "sms", "sound"], timestamp: "2026-06-14T08:42:00+05:30", read: false, archived: false, group: "Emergency", actionHref: "/emergency" },
  { id: "n-003", title: "OPD queue change", message: "MED-020 generated by QR check-in and assigned to Medical OPD.", module: "OPD", priority: "information", roles: ["super_admin", "hospital_admin", "doctor", "nurse", "receptionist"], channels: ["in-app", "push"], timestamp: "2026-06-14T08:50:00+05:30", read: false, archived: false, group: "Queue", actionHref: "/opd" },
  { id: "n-004", title: "Medicine stock shortage", message: "Ventolin inhaler stock is below reorder level. Pharmacy action required.", module: "Pharmacy", priority: "warning", roles: ["super_admin", "hospital_admin", "pharmacist"], channels: ["in-app", "email"], timestamp: "2026-06-14T09:00:00+05:30", read: false, archived: false, group: "Stock", actionHref: "/pharmacy" },
  { id: "n-005", title: "Radiology report completed", message: "CT Brain report is signed and ready for doctor review.", module: "Radiology", priority: "urgent", roles: ["super_admin", "hospital_admin", "doctor", "nurse", "radiologist", "radiology_technician"], channels: ["in-app", "push"], timestamp: "2026-06-14T09:05:00+05:30", read: true, archived: false, group: "Diagnostics", actionHref: "/radiology" },
  { id: "n-006", title: "New appointment booked", message: "Patient booked a diabetes clinic follow-up with Dr. Perera.", module: "Appointments", priority: "information", roles: ["super_admin", "hospital_admin", "doctor", "receptionist", "patient"], channels: ["in-app", "push", "email"], timestamp: "2026-06-14T09:12:00+05:30", read: false, archived: false, group: "Appointments", actionHref: "/appointments" },
  { id: "n-007", title: "Unread secure message", message: "A patient replied in the care message thread.", module: "Secure Chat", priority: "urgent", roles: ["doctor", "nurse", "patient"], channels: ["in-app", "push", "sound"], timestamp: "2026-06-14T09:20:00+05:30", read: false, archived: false, group: "Messages", actionHref: "/portal/messages" },
  { id: "n-008", title: "System backup completed", message: "Nightly backup status is healthy. No failed jobs reported.", module: "ICT Unit", priority: "information", roles: ["super_admin", "hospital_admin"], channels: ["in-app", "email"], timestamp: "2026-06-14T09:30:00+05:30", read: true, archived: false, group: "System", actionHref: "/settings" },
  { id: "n-009", title: "Failed login attempts", message: "Three failed login attempts detected for a staff account.", module: "Security", priority: "warning", roles: ["super_admin", "hospital_admin"], channels: ["in-app", "email", "sound"], timestamp: "2026-06-14T09:44:00+05:30", read: false, archived: false, group: "Security", actionHref: "/audit-logs" },
  { id: "n-010", title: "Bed available", message: "Ward 03 has a bed available after discharge cleaning.", module: "Ward Management", priority: "information", roles: clinical, channels: ["in-app", "push"], timestamp: "2026-06-14T10:02:00+05:30", read: false, archived: false, group: "Admissions", actionHref: "/wards" },
  { id: "n-011", title: "Surgery scheduled", message: "Operating Theatre Complex scheduled an emergency laparotomy at 14:00.", module: "Surgery", priority: "urgent", roles: ["super_admin", "hospital_admin", "doctor", "surgeon", "anesthetist", "nurse"], channels: ["in-app", "push", "sms"], timestamp: "2026-06-14T10:20:00+05:30", read: false, archived: false, group: "Theatre", actionHref: "/operation-theatre" },
  { id: "n-012", title: "Maintenance alert", message: "application hosting maintenance window is planned. ICT staff should monitor status.", module: "System", priority: "warning", roles: allStaff, channels: ["in-app", "email"], timestamp: "2026-06-14T10:40:00+05:30", read: true, archived: false, group: "System", actionHref: "/settings" },
];

function isNotification(value: unknown): value is GovCareNotification {
  if (!value || typeof value !== "object") return false;
  const item = value as Partial<GovCareNotification>;
  return typeof item.id === "string" && typeof item.title === "string" && Array.isArray(item.roles);
}

export function getNotifications() {
  if (typeof window === "undefined") return seedNotifications;
  try {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (!stored) return seedNotifications;
    const parsed: unknown = JSON.parse(stored);
    return Array.isArray(parsed) ? parsed.filter(isNotification) : seedNotifications;
  } catch {
    return seedNotifications;
  }
}

export function saveNotifications(notifications: GovCareNotification[]) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(notifications));
  window.dispatchEvent(new CustomEvent(NOTIFICATIONS_UPDATED_EVENT));
}

export function ensureNotificationsSeeded() {
  if (typeof window === "undefined") return;
  if (!window.localStorage.getItem(STORAGE_KEY)) saveNotifications(seedNotifications);
}

export function addNotification(notification: Omit<GovCareNotification, "id" | "timestamp" | "read" | "archived">) {
  const item: GovCareNotification = {
    ...notification,
    id: crypto.randomUUID(),
    timestamp: new Date().toISOString(),
    read: false,
    archived: false,
  };
  saveNotifications([item, ...getNotifications()].slice(0, 200));
  window.dispatchEvent(new CustomEvent(NOTIFICATION_POPUP_EVENT, { detail: item }));
  playNotificationSound(item.priority);
  if (item.channels.includes("push")) {
    void import("../services/pushService")
      .then(({ showDesktopNotification }) => showDesktopNotification(item))
      .catch(() => false);
  }
  return item;
}

export function updateNotification(id: string, values: Partial<GovCareNotification>) {
  saveNotifications(getNotifications().map((item) => item.id === id ? { ...item, ...values } : item));
}

export function unreadCountForRole(role?: Role) {
  if (!role) return 0;
  return getNotifications().filter((item) => !item.archived && !item.read && item.roles.includes(role)).length;
}

export function playNotificationSound(priority: NotificationPriority) {
  if (typeof window === "undefined") return;
  const AudioContextConstructor = window.AudioContext ?? (window as Window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!AudioContextConstructor) return;
  const context = new AudioContextConstructor();
  const oscillator = context.createOscillator();
  const gain = context.createGain();
  oscillator.connect(gain);
  gain.connect(context.destination);
  oscillator.frequency.value = priority === "critical" ? 880 : priority === "urgent" ? 660 : priority === "warning" ? 520 : 420;
  gain.gain.value = 0.035;
  oscillator.start();
  oscillator.stop(context.currentTime + 0.12);
}
